### ISSUE TITLE
RFC - Component specific CSS

### ISSUE THREAD

**Issue by digitalsadhu** [finn-no/fabric-react#2]
## The (long winded) problem space (for this RPC)

In Troika, components were first class in the sense that it was possible to use markup and core CSS classes to fully implement a component. With Fabric, being more CSS primitive based, the responsibility, as I understand it, lies with the component implementation to assemble the primitives into a working component. To this end, React, Vue and web components are to be provided. This approach will make it more difficult to build something from scratch but will provide a larger set of complete options. To provide a complete example, the slider looks something like this:

```
<div class="relative w-full h-32">
    <div class="track absolute bg-bluegray-300 h-4 top-14 rounded-4 w-full"></div>
    <div class="active-track absolute bg-blue-600 h-4 top-14 rounded-4"></div>
    <div class="thumb absolute w-32 h-32 bottom-0 rounded-full outline-none border-8"></div>
</div>
```

However, these set of classes only gets you half way. Something like the following custom CSS is needed to implement the box shadow on the thumb and the mouseover effect etc.

```css
box-shadow: 0px 0px 4px 0px rgba(0, 0, 0, 0.1), 0px 3px 1px 0px rgba(0, 0, 0, 0.05), 0px 2px 2px 0px rgba(0, 0, 0, 0.05), 0px 3px 3px 0px rgba(0, 0, 0, 0.1);
  &.disabled {
    box-shadow: none;
    pointer-events: none;
  }
  &:hover, &:focus {
    &:before {
      transform: scale(1.3);
    }
  }
  &:before {
    content: '';
    position: absolute;
    background-color: inherit;
    height: 16px;
    width: 16px;
    border-radius: 50%;
    transition: transform 0.1s linear;
  }
```

In order to share the set of classes across component implementations, we now have the [`@finn-no/fabric-classes`](https://github.com/finn-no/fabric-vue/blob/master/packages/fabric-classes/index.js) package. Once added, classes can be set on markup like so:

```
<div class="${classes.wrapper}">
    <div class="${classes.track}"></div>
    <div class="${classes.activeTrack}"></div>
    <div class="${classes.thumb}"></div>
</div>
```

So this is great. Shared classes, less room for inconsistencies and such across the implementations etc. But, what about the remaining CSS work to be done to get the component into a useable state? As it stands, we still need to do this work in multiple places and there's no clear documented way for how to implement the whole component from scratch.

## Thoughts and questions regarding a shared approach

I understand that Fabric itself is not component centric which makes sense but I feel like there's room to explore if it might be possible for some improvement in the component layer maybe. My main question is, since the fabric-classes package already addresses things at the component level, could we find a way to pimp out this package to implement everything needed to implement a component from scratch?

Is it possible to add the rest of the styles to the slider definition object in the package like:
```
export const slider = {
  wrapper: 'relative w-full h-32',
  track: 'track absolute bg-bluegray-300 h-4 top-14 rounded-4 w-full',
  activeTrack: 'active-track absolute bg-blue-600 h-4 top-14 rounded-4',
  activeTrackDisabled: 'bg-bluegray-400 pointer-events-none',
  thumb: 'thumb absolute w-32 h-32 bottom-0 rounded-full outline-none border-8',
  thumbEnabled: 'bg-blue-600 border-white cursor-pointer',
  thumbDisabled: 'disabled bg-bluegray-400 border-bluegray-200 cursor-disabled',
  'customStyles': '.slider { rest of the rules here }',
}
```

and then do something with it in each component?
